import * as z from "zod";
import {
  DEFAULT_PAGE_SIZE,
  MAX_CONTACT_LENGTH,
  MAX_NAME_LENGTH,
  MAX_NOTE_LENGTH,
  MAX_PAGE_SIZE,
  MAX_QUANTITY,
  MAX_RAW_TEXT_LENGTH,
  MAX_UNIT_LENGTH,
  MIN_PASSWORD_LENGTH,
} from "../constants.js";
import { ALL_PERMISSIONS } from "../permissions.js";
import { UnitCodes } from "../units.js";

export const nameSchema = z.string().trim().min(1).max(MAX_NAME_LENGTH);

export const emailSchema = z
  .string()
  .trim()
  .toLowerCase()
  .max(MAX_CONTACT_LENGTH)
  .pipe(z.email());
export const passwordSchema = z
  .string()
  .min(
    MIN_PASSWORD_LENGTH,
    `At least ${MIN_PASSWORD_LENGTH} characters required`,
  )
  .max(200);

export const paginationSchema = z.object({
  pageIndex: z.number().int().min(0),
  pageSize: z.number().int().min(1).max(MAX_PAGE_SIZE),
});
export type Pagination = z.infer<typeof paginationSchema>;

export const DEFAULT_PAGINATION: Pagination = {
  pageIndex: 0,
  pageSize: DEFAULT_PAGE_SIZE,
};

export type Page<TRow> = {
  rows: TRow[];
  rowCount: number;
};

/**
 * Identifiers generated by the client (UUID v7).
 *
 * The prerequisite of offline: an item has identity while you are still
 * between the shelves with no signal, and when the mutation finally leaves,
 * the INSERT is idempotent. The time component also makes ids sortable, which
 * is what lets us order a list by creation without storing a position.
 */
export const entityIdSchema = z.uuid();

/** Better Auth ids are opaque strings, not UUIDs. */
export const userIdSchema = z.string().min(1).max(64);

/** System categories use their slug as id, so this is not a UUID either. */
export const categoryIdSchema = z.string().min(1).max(64);

export const mutationIdSchema = z.uuid();

/**
 * Every queueable mutation carries its own identifier.
 *
 * Without it a retry from the offline queue would apply the same operation
 * twice — and the queue retries until the server answers, which it may well
 * fail to do *after* having applied the write.
 */
export const mutationEnvelope = z.object({ mutationId: mutationIdSchema });
export type MutationEnvelope = z.infer<typeof mutationEnvelope>;

export const rawTextSchema = z.string().trim().min(1).max(MAX_RAW_TEXT_LENGTH);
export const unitCodeSchema = z.enum(UnitCodes);
export const unitTextSchema = z.string().trim().min(1).max(MAX_UNIT_LENGTH);
export const noteSchema = z.string().trim().max(MAX_NOTE_LENGTH);
export const quantitySchema = z
  .number()
  .finite()
  .nonnegative()
  .max(MAX_QUANTITY);

export const permissionsSchema = z
  .number()
  .int()
  .min(0)
  .max(ALL_PERMISSIONS)
  .refine((mask) => (mask & ~ALL_PERMISSIONS) === 0, {
    error: "Unknown permission bit",
  });

export const isoDateTimeSchema = z.iso.datetime({ offset: true });

/** An operation that carries nothing back but its own success. */
export const okSchema = z.object({ ok: z.literal(true) });
