import * as z from "zod";

import { MAX_CHECK_BATCH } from "../constants.js";
import {
  categoryIdSchema,
  entityIdSchema,
  isoDateTimeSchema,
  mutationEnvelope,
  nameSchema,
  noteSchema,
  quantitySchema,
  rawTextSchema,
  unitCodeSchema,
  unitTextSchema,
  userIdSchema,
} from "./common.js";

export const listItemSchema = z.object({
  id: entityIdSchema,
  listId: entityIdSchema,
  /** Exactly what the user typed: the parser may change, history can be re-read. */
  rawText: z.string(),
  name: z.string(),
  quantity: z.number().nullable(),
  /** Canonical code when the unit was recognised... */
  unit: unitCodeSchema.nullable(),
  /** ...the word verbatim when it was not. Never both. */
  unitText: z.string().nullable(),
  note: z.string().nullable(),
  categoryId: categoryIdSchema.nullable(),
  /**
   * Last-write-wins clock over the content group. Carries the device's own
   * instant, clamped to server time, never the moment the write arrived.
   */
  contentUpdatedAt: isoDateTimeSchema,
  /** `null` = still to buy. */
  checkedAt: isoDateTimeSchema.nullable(),
  checkedBy: userIdSchema.nullable(),
  /**
   * A second, independent clock for the checked group.
   *
   * It cannot be folded into `contentUpdatedAt`: that would make every edit
   * made at home invalidate the checks queued from the shop. Nor can
   * `checkedAt` be its own clock, because unchecking sets it to null and
   * leaves nothing to compare a late-arriving check against.
   */
  checkUpdatedAt: isoDateTimeSchema,
  createdAt: isoDateTimeSchema,
  /** Server clock: the sync cursor, never a device timestamp. */
  updatedAt: isoDateTimeSchema,
  /** Tombstone: never a physical delete, or an offline client resurrects it. */
  deletedAt: isoDateTimeSchema.nullable(),
});
export type ListItem = z.infer<typeof listItemSchema>;

/**
 * The whole content group travels on every write.
 *
 * Under group last-write-wins a partial update is ill-defined: editing only
 * the note would still stamp the group and silently discard a quantity edit
 * still sitting in the queue. The client holds the complete item in its
 * offline cache, so sending all of it costs nothing.
 */
const itemContentShape = {
  rawText: rawTextSchema,
  name: nameSchema,
  quantity: quantitySchema.nullable(),
  unit: unitCodeSchema.nullable(),
  unitText: unitTextSchema.nullable(),
  note: noteSchema.nullable(),
  categoryId: categoryIdSchema.nullable(),
};

const exclusiveUnit = (value: {
  unit: string | null;
  unitText: string | null;
}): boolean => value.unit === null || value.unitText === null;

const UNIT_EXCLUSIVE_ERROR = "A unit is either canonical or raw, never both";

export const addItemInputSchema = mutationEnvelope
  .extend({
    listId: entityIdSchema,
    /** Generated by the client before the network is even consulted. */
    id: entityIdSchema,
    contentUpdatedAt: isoDateTimeSchema,
  })
  .extend(itemContentShape)
  .refine(exclusiveUnit, { error: UNIT_EXCLUSIVE_ERROR });
export type AddItemInput = z.infer<typeof addItemInputSchema>;

export const updateItemInputSchema = mutationEnvelope
  .extend({
    listId: entityIdSchema,
    id: entityIdSchema,
    contentUpdatedAt: isoDateTimeSchema,
  })
  .extend(itemContentShape)
  .refine(exclusiveUnit, { error: UNIT_EXCLUSIVE_ERROR });
export type UpdateItemInput = z.infer<typeof updateItemInputSchema>;

export const deleteItemInputSchema = mutationEnvelope.extend({
  listId: entityIdSchema,
  id: entityIdSchema,
  at: isoDateTimeSchema,
});
export type DeleteItemInput = z.infer<typeof deleteItemInputSchema>;

/**
 * Checking is last-write-wins on its own clock and needs no version: it is
 * idempotent and cannot corrupt anything. `checkedAt` is the instant the
 * device recorded, not the instant the server heard about it — a tick made in
 * the shop at 18:03 and synced at 18:40 must not beat an untick made at 18:20.
 */
export const checkItemInputSchema = mutationEnvelope.extend({
  listId: entityIdSchema,
  id: entityIdSchema,
  checkedAt: isoDateTimeSchema,
});
export type CheckItemInput = z.infer<typeof checkItemInputSchema>;

export const uncheckItemInputSchema = mutationEnvelope.extend({
  listId: entityIdSchema,
  id: entityIdSchema,
  at: isoDateTimeSchema,
});
export type UncheckItemInput = z.infer<typeof uncheckItemInputSchema>;

/** Draining the offline queue: many ticks in one round trip. */
export const checkManyInputSchema = mutationEnvelope.extend({
  checks: z
    .array(
      z.object({
        listId: entityIdSchema,
        id: entityIdSchema,
        /** `null` means uncheck. */
        checkedAt: isoDateTimeSchema.nullable(),
        at: isoDateTimeSchema,
      }),
    )
    .min(1)
    .max(MAX_CHECK_BATCH),
});
export type CheckManyInput = z.infer<typeof checkManyInputSchema>;

export const listItemsInputSchema = z.object({
  listId: entityIdSchema,
  /** Tombstones included: only the offline reconciliation asks for them. */
  includeDeleted: z.boolean().default(false),
});
export type ListItemsInput = z.infer<typeof listItemsInputSchema>;

/**
 * What a write did.
 *
 * `stale` is not an error and never travels as one: the server kept what it
 * had, hands it back, and the client adopts it. That is the point of having
 * dropped optimistic locking — twenty queued edits produce at most twenty
 * silent `stale` results instead of twenty modal dialogs.
 */
export const WriteOutcome = {
  applied: "applied",
  stale: "stale",
  deduplicated: "deduplicated",
} as const;
export type WriteOutcome = (typeof WriteOutcome)[keyof typeof WriteOutcome];
export const WriteOutcomes = [
  WriteOutcome.applied,
  WriteOutcome.stale,
  WriteOutcome.deduplicated,
] as const;

export const itemWriteResultSchema = z.object({
  outcome: z.enum(WriteOutcomes),
  item: listItemSchema,
  /**
   * Lets the client measure and correct its own clock offset.
   *
   * Clamping only rescues a device that is ahead; one that is behind would see
   * every write silently discarded, and by design there is no conflict dialog
   * left to tell it so.
   */
  serverTime: isoDateTimeSchema,
});
export type ItemWriteResult = z.infer<typeof itemWriteResultSchema>;

/**
 * A suggestion carries no product id.
 *
 * Picking one creates an ordinary item with a client-generated id, and the
 * server re-resolves the catalogue entry from the name — so the internal
 * catalogue never leaks, and the client never has an id to reconcile.
 */
export const suggestionSchema = z.object({
  name: z.string(),
  categoryId: categoryIdSchema.nullable(),
  lastQuantity: z.number().nullable(),
  lastUnit: unitCodeSchema.nullable(),
  lastUnitText: z.string().nullable(),
  useCount: z.number().int().nonnegative(),
  lastUsedAt: isoDateTimeSchema,
});
export type Suggestion = z.infer<typeof suggestionSchema>;
