import {
  check,
  index,
  numeric,
  pgTable,
  text,
  timestamp,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { UnitCodes } from "@pantry/shared";
import { categories } from "./categories.js";
import { lists } from "./lists.js";
import { products } from "./products.js";
import { shoppingSessions } from "./shopping-sessions.js";
import { users } from "./users.js";

export const listItems = pgTable(
  "list_items",
  {
    /**
     * UUID v7 generated by the client, before the network is consulted.
     *
     * The prerequisite of offline, and, because the first 48 bits are a
     * timestamp, the reason there is no sort_order: ordering by id IS ordering
     * by creation, for free, with no multi-row renumbering to go wrong in the
     * offline queue.
     */
    id: text("id").primaryKey(),
    listId: text("list_id")
      .notNull()
      .references(() => lists.id, { onDelete: "cascade" }),

    /** Exactly what was typed. The parser may change, history can be re-read. */
    rawText: text("raw_text").notNull(),
    name: text("name").notNull(),
    quantity: numeric("quantity", { mode: "number" }),
    /** Canonical code when the unit was recognised... */
    unit: text("unit", { enum: UnitCodes }),
    /** ...the word verbatim when it was not. Never both. */
    unitText: text("unit_text"),
    note: text("note"),
    categoryId: text("category_id").references(() => categories.id, {
      onDelete: "set null",
    }),

    /** Resolved server-side only; the item never depends on it to display. */
    productId: text("product_id").references(() => products.id, {
      onDelete: "set null",
    }),

    /**
     * Last-write-wins clock over name/quantity/unit/unitText/note/category.
     *
     * Carries the writing device's own instant, clamped to server time. A
     * write applies only when it is at least as new as what is stored, and a
     * skipped write is not an error: the server hands back what it holds and
     * the client adopts it.
     */
    contentUpdatedAt: timestamp("content_updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),

    /** NULL means still to buy. */
    checkedAt: timestamp("checked_at", { withTimezone: true }),
    checkedBy: text("checked_by").references(() => users.id, {
      onDelete: "set null",
    }),
    /**
     * Which shopping run this was ticked during, resolved by WHEN the device
     * recorded it rather than by whatever session happens to be open at sync
     * time, otherwise a run taken over while the shopper was offline would
     * attribute their ticks to whoever took it.
     */
    checkedIn: text("checked_in").references(() => shoppingSessions.id, {
      onDelete: "set null",
    }),
    /**
     * A second, independent clock, for the checked group alone.
     *
     * It cannot share contentUpdatedAt: that would make an edit at home
     * invalidate the ticks queued in the shop, which is the coupling group-LWW
     * exists to break. And checkedAt cannot be its own clock, because
     * unticking sets it to NULL and leaves nothing for a late tick to lose to.
     */
    checkUpdatedAt: timestamp("check_updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),

    createdBy: text("created_by").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** Server clock: the sync cursor, never a device timestamp. */
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** Tombstone: never a physical delete, or an offline client resurrects it. */
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (table) => [
    check(
      "list_items_unit_exclusive_check",
      sql`${table.unit} IS NULL OR ${table.unitText} IS NULL`,
    ),
    check(
      "list_items_quantity_check",
      sql`${table.quantity} IS NULL OR ${table.quantity} >= 0`,
    ),
    check(
      "list_items_checked_check",
      sql`(${table.checkedAt} IS NULL) = (${table.checkedBy} IS NULL)`,
    ),
    index("idx_list_items_list")
      .on(table.listId)
      .where(sql`${table.deletedAt} IS NULL`),
    /** Reserved for a future sync.since(listId, timestamp). */
    index("idx_list_items_sync").on(table.listId, table.updatedAt),
    index("idx_list_items_session")
      .on(table.checkedIn)
      .where(sql`${table.checkedIn} IS NOT NULL`),
    index("idx_list_items_product").on(table.productId),
  ],
);
